### PR TITLE
Fix rendering of landscape-orientation PDF files on iOS.

### PR DESCRIPTION
**Pull request by andresath**
Those PDF files where pages are in landscape orientation are rendered incorrectly in portrait mode, making it difficult to read and/or interpret.

The fix to this issue is to use the `rotationAngle` of the `CGPDFPage` instance, and based on it, perform a rotation on the `CGContext` so the bitmap gets rendered in the correct orientation.

### Before
Simulator Screen Shot - iPhone 11 - 2020-11-13 at 15 37 56

### After
Simulator Screen Shot - iPhone 11 - 2020-11-13 at 15 39 33

### CODE REVIEW

**Comment by andresath** [comment]
Hello @SergeShkurko! I've created this PR to address an issue I've faced for those PDF files that have pages in landscape orientation, I'd really appreciate if you can check it out at your earliest convenience :D Thanks a lot!

**Comment by SergeShkurko** [comment]
@andresath can you attach pdf file from screenshots?

**Comment by andresath** [comment]
@SergeShkurko Thanks a lot for reviewing and merging this PR! As per your request, here's the PDF document I used to test the changes.

[sample-landscape.pdf](https://github.com/rbcprolabs/packages.flutter/files/5655017/sample-landscape.pdf)

**Comment by SergeShkurko** [comment]
@andresath thank you for your help :)

**Pull request merged**
