### PR TITLE
cast error while ExplorerLocalizationsDelegate() + french support

### PR DESCRIPTION
**Pull request by EmixamPP**
fix : `Unhandled Exception: type '() => Future<dynamic>' is not a subtype of type '() => Future<Object>' in type cast`

The explorer pluggin does not work. At least under  (I haven't tried an older version) : 
```
Flutter 2.2.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b22742018b (il y a 11 jours) • 2021-05-14 19:12:57 -0700
Engine • revision a9d88a4d18
Tools • Dart 2.13.0
```
A cast error is caused by : `localizationsDelegates: [ExplorerLocalizationsDelegate()]`

I did a quick fix by removing the forced cast to let the dynamic conversion do it.

I know that this code has been generated via `package:intl/generate_localized.dart` but at least now it works.

### CODE REVIEW

**Comment by EmixamPP** [comment]
Sorry for the "french support" commit, I wanted to make a separate pull request but I didn't pay attention to the fact that it would update the one I already made.

**Comment by EmixamPP** [comment]
I also noticed that the ability to translate "Add" on the "+" button is missing.

**Comment by SergeShkurko** [comment]
Thanks for you contribution!

**Comment by SergeShkurko** [comment]
@EmixamPP update published at pub.dev (2.1.0)

https://pub.dev/packages/explorer/versions/2.1.0

**Comment by EmixamPP** [comment]
Nice !

**Pull request merged**
