### PR TITLE
Update epub_cfi_reader.dart

### PR DESCRIPTION
**Pull request by kirit0-kun**
Self ending tags are not supported.
The parser makes them wrap their next siblings.

### CODE REVIEW

**Comment by SergeShkurko** [comment]
@kirit0-kun can you attach html examples with wrong code and resolved by regexp result?

**Comment by kirit0-kun** [comment]
You’ll find an example attached

**Comment by SergeShkurko** [comment]
still do not understand

for example regexp makes from `<image ... />` -> `<image ..></image>` ?

**Comment by kirit0-kun** [comment]
if you're working with a google doc generated epub file, it make bookmarks and destinations self ending <a> tags.
The parser treats them as normal tags and encloses their siblings inside them so for instance:

```
<a id="some-section"/>
<h1>Some header</h1>
```

becomes:
```
<a id="some-section">
<h1>Some header</h1>
</a>
```

but if you change <a id=""/> into <a id=""></a> this doesn't happen.

**Comment by SergeShkurko** [comment]
@kirit0-kun thanks for you contribution!

**Pull request merged**
